--- 
artifacts: 
  discard-paths: true
  files: 
    - target/*.*
phases: 
  build: 
    commands: 
      - "echo Entered the build phase..."
      - "echo Build started on `date`"
      - "mvn install"
version: 0.2
